// Seeding data for modelRate table in Database 

interface ModelPricing {
  modelId: string;
  provider:
    | "openai"
    | "anthropic"
    | "google"
    | "meta"
    | "mistralai"
    | "xai"
    | "deepseek"
    | "alibaba"
    | "moonshotai";
  inputRateUSD: number;
  outputRateUSD: number;
  minTier: "free" | "pro";
  usecase: "text" | "image";
}

const modelPricing: ModelPricing[] = [
  {
    modelId: "openai/gpt-5.5",
    provider: "openai",
    inputRateUSD: 5.0,
    outputRateUSD: 30.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-5.5-pro",
    provider: "openai",
    inputRateUSD: 30.0,
    outputRateUSD: 180.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-5.4",
    provider: "openai",
    inputRateUSD: 2.5,
    outputRateUSD: 15.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-5.4-pro",
    provider: "openai",
    inputRateUSD: 30.0,
    outputRateUSD: 180.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-5.4-mini",
    provider: "openai",
    inputRateUSD: 0.75,
    outputRateUSD: 4.5,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-5.4-nano",
    provider: "openai",
    inputRateUSD: 0.2,
    outputRateUSD: 1.25,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-5",
    provider: "openai",
    inputRateUSD: 1.25,
    outputRateUSD: 10.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-4.1",
    provider: "openai",
    inputRateUSD: 2.0,
    outputRateUSD: 8.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-4.1-mini",
    provider: "openai",
    inputRateUSD: 0.4,
    outputRateUSD: 1.6,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-4o",
    provider: "openai",
    inputRateUSD: 2.5,
    outputRateUSD: 10.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/gpt-4o-mini",
    provider: "openai",
    inputRateUSD: 0.15,
    outputRateUSD: 0.6,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/o4-mini",
    provider: "openai",
    inputRateUSD: 1.1,
    outputRateUSD: 4.4,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "openai/o3",
    provider: "openai",
    inputRateUSD: 2.0,
    outputRateUSD: 8.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "anthropic/claude-haiku-4.5",
    provider: "anthropic",
    inputRateUSD: 1.0,
    outputRateUSD: 5.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "anthropic/claude-sonnet-4.5",
    provider: "anthropic",
    inputRateUSD: 3.0,
    outputRateUSD: 15.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "anthropic/claude-opus-4.8",
    provider: "anthropic",
    inputRateUSD: 5.0,
    outputRateUSD: 25.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "google/gemini-3.1-pro",
    provider: "google",
    inputRateUSD: 2.0,
    outputRateUSD: 12.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "google/gemini-3-flash",
    provider: "google",
    inputRateUSD: 0.5,
    outputRateUSD: 3.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "google/gemini-3.1-flash-lite",
    provider: "google",
    inputRateUSD: 0.25,
    outputRateUSD: 1.5,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "google/gemini-2.5-pro",
    provider: "google",
    inputRateUSD: 1.25,
    outputRateUSD: 10.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "google/gemini-2.5-flash",
    provider: "google",
    inputRateUSD: 0.3,
    outputRateUSD: 2.5,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "google/gemini-2.5-flash-lite",
    provider: "google",
    inputRateUSD: 0.1,
    outputRateUSD: 0.4,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "@cf/google/gemma-4-26b-a4b-it",
    provider: "google",
    inputRateUSD: 0.1,
    outputRateUSD: 0.3,
    minTier: "free",
    usecase: "text",
  },
  {
    modelId: "@cf/meta/llama-4-scout-17b-16e-instruct",
    provider: "meta",
    inputRateUSD: 0.27,
    outputRateUSD: 0.85,
    minTier: "free",
    usecase: "text",
  },
  {
    modelId: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    provider: "meta",
    inputRateUSD: 0.29,
    outputRateUSD: 2.25,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "@cf/meta/llama-3.2-11b-vision-instruct",
    provider: "meta",
    inputRateUSD: 0.049,
    outputRateUSD: 0.68,
    minTier: "free",
    usecase: "text",
  },
  {
    modelId: "@cf/mistralai/mistral-small-3.1-24b-instruct",
    provider: "mistralai",
    inputRateUSD: 0.35,
    outputRateUSD: 0.56,
    minTier: "free",
    usecase: "text",
  },
  {
    modelId: "@cf/mistral/mistral-7b-instruct-v0.2-lora",
    provider: "mistralai",
    inputRateUSD: 0.4,
    outputRateUSD: 0.5,
    minTier: "free",
    usecase: "text",
  },
  {
    modelId: "xai/grok-4.3",
    provider: "xai",
    inputRateUSD: 1.25,
    outputRateUSD: 2.5,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "xai/grok-4.20-multi-agent-0309",
    provider: "xai",
    inputRateUSD: 2.0,
    outputRateUSD: 6.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "xai/grok-4.20-0309-reasoning",
    provider: "xai",
    inputRateUSD: 2.0,
    outputRateUSD: 6.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "xai/grok-4.20-0309-non-reasoning",
    provider: "xai",
    inputRateUSD: 2.0,
    outputRateUSD: 6.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    provider: "deepseek",
    inputRateUSD: 0.5,
    outputRateUSD: 4.88,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "alibaba/qwen3-max",
    provider: "alibaba",
    inputRateUSD: 1.2,
    outputRateUSD: 6.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "alibaba/qwen3.5-397b-a17b",
    provider: "alibaba",
    inputRateUSD: 0.6,
    outputRateUSD: 3.6,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "@cf/qwen/qwq-32b",
    provider: "alibaba",
    inputRateUSD: 0.66,
    outputRateUSD: 1.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "@cf/qwen/qwen3-30b-a3b-fp8",
    provider: "alibaba",
    inputRateUSD: 0.051,
    outputRateUSD: 0.34,
    minTier: "free",
    usecase: "text",
  },
  {
    modelId: "@cf/qwen/qwen2.5-coder-32b-instruct",
    provider: "alibaba",
    inputRateUSD: 0.66,
    outputRateUSD: 1.0,
    minTier: "pro",
    usecase: "text",
  },
  {
    modelId: "@cf/moonshotai/kimi-k2.6",
    provider: "moonshotai",
    inputRateUSD: 0.95,
    outputRateUSD: 4.0,
    minTier: "pro",
    usecase: "text",
  },
];
