// ─────────────────────────────────────────────────────────────
// If running locally against local D1:
//   npx wrangler d1 execute <DB_NAME> --local --file=./scripts/seed.sql
//
// If seeding programmatically via wrangler's unstable_dev or
// drizzle directly, use the approach below.
// ─────────────────────────────────────────────────────────────

export const models = [
  // ── OPENAI ──────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5.5",
    provider: "openai",
    rawInputRateUSD: 5.0,
    rawOutputRateUSD: 30.0,
    inputRateUSD: 9.5,
    outputRateUSD: 57.0,
    imageRateUSD: null,
    markupMultiplier: 1.9,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5.5-pro",
    provider: "openai",
    rawInputRateUSD: 30.0,
    rawOutputRateUSD: 180.0,
    inputRateUSD: 57.0,
    outputRateUSD: 342.0,
    imageRateUSD: null,
    markupMultiplier: 1.9,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5.4",
    provider: "openai",
    rawInputRateUSD: 2.5,
    rawOutputRateUSD: 15.0,
    inputRateUSD: 4.38,
    outputRateUSD: 26.25,
    imageRateUSD: null,
    markupMultiplier: 1.75,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5.4-pro",
    provider: "openai",
    rawInputRateUSD: 30.0,
    rawOutputRateUSD: 180.0,
    inputRateUSD: 57.0,
    outputRateUSD: 342.0,
    imageRateUSD: null,
    markupMultiplier: 1.9,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5.4-mini",
    provider: "openai",
    rawInputRateUSD: 0.75,
    rawOutputRateUSD: 4.5,
    inputRateUSD: 1.01,
    outputRateUSD: 6.08,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5.4-nano",
    provider: "openai",
    rawInputRateUSD: 0.2,
    rawOutputRateUSD: 1.25,
    inputRateUSD: 0.27,
    outputRateUSD: 1.69,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-5",
    provider: "openai",
    rawInputRateUSD: 1.25,
    rawOutputRateUSD: 10.0,
    inputRateUSD: 2.0,
    outputRateUSD: 16.0,
    imageRateUSD: null,
    markupMultiplier: 1.6,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-4.1",
    provider: "openai",
    rawInputRateUSD: 2.0,
    rawOutputRateUSD: 8.0,
    inputRateUSD: 3.0,
    outputRateUSD: 12.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-4.1-mini",
    provider: "openai",
    rawInputRateUSD: 0.4,
    rawOutputRateUSD: 1.6,
    inputRateUSD: 0.54,
    outputRateUSD: 2.16,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-4o",
    provider: "openai",
    rawInputRateUSD: 2.5,
    rawOutputRateUSD: 10.0,
    inputRateUSD: 3.75,
    outputRateUSD: 15.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/gpt-4o-mini",
    provider: "openai",
    rawInputRateUSD: 0.15,
    rawOutputRateUSD: 0.6,
    inputRateUSD: 0.2,
    outputRateUSD: 0.81,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/o4-mini",
    provider: "openai",
    rawInputRateUSD: 1.1,
    rawOutputRateUSD: 4.4,
    inputRateUSD: 1.49,
    outputRateUSD: 5.94,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "openai/o3",
    provider: "openai",
    rawInputRateUSD: 2.0,
    rawOutputRateUSD: 8.0,
    inputRateUSD: 3.0,
    outputRateUSD: 12.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── ANTHROPIC ───────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "anthropic/claude-haiku-4.5",
    provider: "anthropic",
    rawInputRateUSD: 1.0,
    rawOutputRateUSD: 5.0,
    inputRateUSD: 1.35,
    outputRateUSD: 6.75,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "anthropic/claude-sonnet-4.5",
    provider: "anthropic",
    rawInputRateUSD: 3.0,
    rawOutputRateUSD: 15.0,
    inputRateUSD: 4.5,
    outputRateUSD: 22.5,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "anthropic/claude-opus-4.8",
    provider: "anthropic",
    rawInputRateUSD: 5.0,
    rawOutputRateUSD: 25.0,
    inputRateUSD: 8.75,
    outputRateUSD: 43.75,
    imageRateUSD: null,
    markupMultiplier: 1.75,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── GOOGLE ──────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "google/gemini-3.1-pro",
    provider: "google",
    rawInputRateUSD: 2.0,
    rawOutputRateUSD: 12.0,
    inputRateUSD: 3.2,
    outputRateUSD: 19.2,
    imageRateUSD: null,
    markupMultiplier: 1.6,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "google/gemini-3-flash",
    provider: "google",
    rawInputRateUSD: 0.5,
    rawOutputRateUSD: 3.0,
    inputRateUSD: 0.68,
    outputRateUSD: 4.05,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "google/gemini-3.1-flash-lite",
    provider: "google",
    rawInputRateUSD: 0.25,
    rawOutputRateUSD: 1.5,
    inputRateUSD: 0.34,
    outputRateUSD: 2.03,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "google/gemini-2.5-pro",
    provider: "google",
    rawInputRateUSD: 1.25,
    rawOutputRateUSD: 10.0,
    inputRateUSD: 2.0,
    outputRateUSD: 16.0,
    imageRateUSD: null,
    markupMultiplier: 1.6,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "google/gemini-2.5-flash",
    provider: "google",
    rawInputRateUSD: 0.3,
    rawOutputRateUSD: 2.5,
    inputRateUSD: 0.41,
    outputRateUSD: 3.38,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "google/gemini-2.5-flash-lite",
    provider: "google",
    rawInputRateUSD: 0.1,
    rawOutputRateUSD: 0.4,
    inputRateUSD: 0.14,
    outputRateUSD: 0.54,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/google/gemma-4-26b-a4b-it",
    provider: "google",
    rawInputRateUSD: 0.1,
    rawOutputRateUSD: 0.3,
    inputRateUSD: 0.12,
    outputRateUSD: 0.36,
    imageRateUSD: null,
    markupMultiplier: 1.2,
    minTier: "free" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── META ────────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "@cf/meta/llama-4-scout-17b-16e-instruct",
    provider: "meta",
    rawInputRateUSD: 0.27,
    rawOutputRateUSD: 0.85,
    inputRateUSD: 0.32,
    outputRateUSD: 1.02,
    imageRateUSD: null,
    markupMultiplier: 1.2,
    minTier: "free" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    provider: "meta",
    rawInputRateUSD: 0.29,
    rawOutputRateUSD: 2.25,
    inputRateUSD: 0.39,
    outputRateUSD: 3.04,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/meta/llama-3.2-11b-vision-instruct",
    provider: "meta",
    rawInputRateUSD: 0.049,
    rawOutputRateUSD: 0.68,
    inputRateUSD: 0.059,
    outputRateUSD: 0.816,
    imageRateUSD: null,
    markupMultiplier: 1.2,
    minTier: "free" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── MISTRAL ─────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "@cf/mistralai/mistral-small-3.1-24b-instruct",
    provider: "mistralai",
    rawInputRateUSD: 0.35,
    rawOutputRateUSD: 0.56,
    inputRateUSD: 0.42,
    outputRateUSD: 0.67,
    imageRateUSD: null,
    markupMultiplier: 1.2,
    minTier: "free" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/mistral/mistral-7b-instruct-v0.2-lora",
    provider: "mistralai",
    rawInputRateUSD: 0.4,
    rawOutputRateUSD: 0.5,
    inputRateUSD: 0.48,
    outputRateUSD: 0.6,
    imageRateUSD: null,
    markupMultiplier: 1.2,
    minTier: "free" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── XAI ─────────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "xai/grok-4.3",
    provider: "xai",
    rawInputRateUSD: 1.25,
    rawOutputRateUSD: 2.5,
    inputRateUSD: 1.69,
    outputRateUSD: 3.38,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "xai/grok-4.20-multi-agent-0309",
    provider: "xai",
    rawInputRateUSD: 2.0,
    rawOutputRateUSD: 6.0,
    inputRateUSD: 3.0,
    outputRateUSD: 9.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "xai/grok-4.20-0309-reasoning",
    provider: "xai",
    rawInputRateUSD: 2.0,
    rawOutputRateUSD: 6.0,
    inputRateUSD: 3.0,
    outputRateUSD: 9.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "xai/grok-4.20-0309-non-reasoning",
    provider: "xai",
    rawInputRateUSD: 2.0,
    rawOutputRateUSD: 6.0,
    inputRateUSD: 3.0,
    outputRateUSD: 9.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── DEEPSEEK ────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    provider: "deepseek",
    rawInputRateUSD: 0.5,
    rawOutputRateUSD: 4.88,
    inputRateUSD: 0.68,
    outputRateUSD: 6.59,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── ALIBABA / QWEN ──────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "alibaba/qwen3-max",
    provider: "alibaba",
    rawInputRateUSD: 1.2,
    rawOutputRateUSD: 6.0,
    inputRateUSD: 1.8,
    outputRateUSD: 9.0,
    imageRateUSD: null,
    markupMultiplier: 1.5,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "alibaba/qwen3.5-397b-a17b",
    provider: "alibaba",
    rawInputRateUSD: 0.6,
    rawOutputRateUSD: 3.6,
    inputRateUSD: 0.81,
    outputRateUSD: 4.86,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/qwen/qwq-32b",
    provider: "alibaba",
    rawInputRateUSD: 0.66,
    rawOutputRateUSD: 1.0,
    inputRateUSD: 0.89,
    outputRateUSD: 1.35,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/qwen/qwen3-30b-a3b-fp8",
    provider: "alibaba",
    rawInputRateUSD: 0.051,
    rawOutputRateUSD: 0.34,
    inputRateUSD: 0.061,
    outputRateUSD: 0.408,
    imageRateUSD: null,
    markupMultiplier: 1.2,
    minTier: "free" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    modelId: "@cf/qwen/qwen2.5-coder-32b-instruct",
    provider: "alibaba",
    rawInputRateUSD: 0.66,
    rawOutputRateUSD: 1.0,
    inputRateUSD: 0.89,
    outputRateUSD: 1.35,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── MOONSHOT ────────────────────────────────────────────────
  {
    id: crypto.randomUUID(),
    modelId: "@cf/moonshotai/kimi-k2.6",
    provider: "moonshotai",
    rawInputRateUSD: 0.95,
    rawOutputRateUSD: 4.0,
    inputRateUSD: 1.28,
    outputRateUSD: 5.4,
    imageRateUSD: null,
    markupMultiplier: 1.35,
    minTier: "pro" as const,
    usecase: "text" as const,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];